### ISSUE TITLE
FEAT(analytics): MVP Analytics Questions

### ISSUE THREAD

**Issue by alfl** [kubelt/kubelt#1271]
# Why

In order to measure progress against business goals, for internal and external reporting use, we intend to collect various data sets and from those generate metrics.

# What

- Collect web analytics data on the marketing landing pages and web applications (profile, passport, console) so that we can answer questions regarding UTM performance and top-of-funnel. Engineering team can use metrics here to determine platform support (device and browser versions, etc).
- Documentation analytics are a separate tech stack (gitbook) -- figure out how to integrate them.
- Collect worker analytics / logpush analytics so that we can measure conversion to usage of the various services, including node creation.

# How

- [x] Add Cloudflare Web Analytics to the marketing sites
- [x] Add Cloudflare Web Analytics to Profile
- [x] Add Cloudflare Web Analytics to Passport
- [x] Add Cloudflare Web Analytics to Console
- [x] Can Cloudflare Web Analytics be connected to Grafana?
- [x] Can Cloudflare Web Analytics be connected to Logpush?
- [x] Request access to Workers Analytics Engine (WAE)
- [x] Configure Workers Analytics Engine for all services (ie, address, account, etc., perhaps sub-ticket these)
- [x] Determine if Logpush can serve in place for WAE
- [x] Determine if Logpush can be an endpoint for Cloudflare Web Analytics
- [x] Determine if Cloudflare Web Analytics have traceability through workers analytics (perhaps via Ray ID)
- [x] Determine if/how Cloudflare Web Analytics supports UTM tracking.
- [x] Would another tool enable UTMs?
- [x] Determine how often address/account nodes are accessed (MAU measure)
- [x] Determine address nodes per account node (intensivity measure)
- [x] Determine rates of change of node accesses and creation (intensivity/extensivity growth).
- [x] Determine how/if Gitbook analytics integrate (Ray IDs from CF cache)?
- [x] Rates of GraphQL API Key use.
- [x] Rates of JWT use / refresh counts.

# Notes

- https://developers.cloudflare.com/analytics/

**Comment by crimeminister** [comment]
Can we link external reporting to an API key, and expose that information to the user in `console`?

**Comment by alfl** [comment]
cum address
tot account
mau / dau (requests to profile, logins (into product X), segment on dev vs user)
