### ISSUE TITLE
 feat(sdk): Connect SDK auth flow to API

### ISSUE THREAD

**Issue by billkube** [kubelt/kubelt#150]
Use HTTP, crypto and jwt libs in the sdk to connect authenticate, and register calls to the miniflare worker. For now i will just test the node http client. Tracking in pr #149

**Comment by Cosmin-Parvulescu** [comment]
Still, as of today, when trying to call the authenticate function, there is still an error being thrown preventing the full e2e authentication flow. The error, as seen in the console, possibly suggests a mismatch in configuration / call structure.

I have opened a bug report to facilitate tracking: https://github.com/kubelt/kubelt/issues/265

**Comment by billkube** [comment]
e2e auth flow now working in browser context
