### ISSUE TITLE
BUG([sdk]): ddt wallet regression

### ISSUE THREAD

**Issue by billkube** [kubelt/kubelt#329]
## I'm submitting a ...

- [x] bug report
- [ ] feature request

## What is the current behavior?
ddt does not show wallet in ddt wallet ls. it also fails when running ddt p2p auth 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
`$ ddt wallet init walletname 
(works) 
$ ddt wallet ls 
(no output) 
$ ddt p2p auth -p 8787 0x45a5e14eaf2f505067df379a6f527113b35afc0d -w testing
Enter your password:  ****

Error: ENOENT: no such file or directory, open '/home/billk/.local/share/ddt/wallets/testing'
    at Object.openSync (node:fs:585:3)
...
`
## What is the expected behavior?
should find the wallet in the correct directory 

## Please tell us about your environment:

Ubuntu 20.04.4 LTS

Version:
Browser or OS:

**Comment by crimeminister** [comment]
Thus may be related to a recent change in the location of wallet files. Feel free to also assign to me if you'd like.

**Comment by crimeminister** [comment]
Fixed on linked PR
