### ISSUE TITLE
FEAT(TS): Refactor the CLJS Application to TypeScript

### ISSUE THREAD

**Issue by alfl** [kubelt/kubelt#551]
# Why

3iD is intended to have high DX and serve as a developer relations/marketing piece and as a demo application.

# What

The current CLJS prototype should be refactored into TypeScript (larger community) as it is moved into the monorepo.

# How

- [x] Framework (Expo; handled in #565)
- [ ] #550
- [x] kubelt/kubelt#549
- [x] #611
- [x] #612
- [x] #610
- [ ] Implement Gallery Screen
- [ ] Validate OG Tags Still Work

**Comment by alfl** [comment]
The initial translation should be 1:1, but we're going to extend the features over time. Yes, should also be moved to Expo.

**Comment by Cosmin-Parvulescu** [comment]
> @Cosmin-Parvulescu cleaned up **How** and added two points about the gallery screen and validating the OG tags.
> 
> Do we need to ticket the "Wallet Connection" button (ie, the one that is labelled with the wallet address), or is that considered part of the navigation menu?

Added a comment to the Nav menu

**Comment by alfl** [comment]
This is ongoing work and this ticket doesn't seem useful. Closing.
