### ISSUE TITLE
FEAT(gate): Passing the Early Access Gate

### ISSUE THREAD

**Issue by alfl** [kubelt/kubelt#560]
# Why

We want users to be able to pass through the Early Access gate.

# What

Using the [Access Gate Interface](https://www.notion.so/kubelt/Access-Gate-Interface-584b221a6f7944b6a3cc6d25a4b817c9), allow users to pass through the access gate to the profile page.

# How

There are various points throughout the application where we might want to check in real-time what kind of claims the currently authenticated user posesses. As such, there should be a method added to the kubelt provider that allows us to query Oort in order to get a string-list of claims. 

- [x] #563
- [x] #574

If the user's response contains the proper claim (`3iD.enter`?), they should be redirected to the #549 CLJS extracted profile screen. As far as I can tell, the flow is Landing -> Auth -> CHECK CLAIMS after which, it's either:
- Has claims, GO TO profile screen;
- Not has claims, GO TO gate screen (2C).

- [ ] Redirect users to profile screen if they have proper claim (handled in #600)

- [x] #599

# Notes

- https://www.notion.so/kubelt/Access-Gate-Interfaces-584b221a6f7944b6a3cc6d25a4b817c9

**Comment by alfl** [comment]
Looks good, flow is right. It's going to get a little more complex when we add mint PFP so make sure the handoff to the profile screen is configurable.

**Comment by Cosmin-Parvulescu** [comment]
> Looks good, flow is right. It's going to get a little more complex when we add mint PFP so make sure the handoff to the profile screen is configurable.

I'm hoping `navigation.navigate('Mint')` or `navigation.navigate('ProfileDetails')` will do the trick. :)

**Comment by alfl** [comment]
Closed/fixed.
