### ISSUE TITLE
FEAT(dd): Add `data-dd-action-name` to wallet button

### ISSUE THREAD

**Issue by alfl** [kubelt/kubelt#571]
# Why

In order to make decisions based on data the data need to be clean.

# What

Most/all application screens have a "wallet button" in the top-right corner that looks something like this:

![image](https://user-images.githubusercontent.com/9158102/179838962-5bd1cccc-c974-4742-a00f-30a2ffa1ea0f.png)

The button text changes depending on what wallet address is connected. DataDog names user actions based on button text, so each wallet address ends up being tracked uniquely (~per-user). Instead we want all user interactions with this button to be aggregated.

[We do this by adding `data-dd-action-name`](https://www.notion.so/kubelt/DataDog-Analytics-Schema-0f92f08f72fd4b6a9bc528cd38d02765#c6298b12a46e43c9b3d1cf51d66d47be) to the relevant DOM element.

# How

- [ ] Add `data-dd-action-name='wallet-button'` as an attribute to this button.

# Notes

- https://www.notion.so/kubelt/DataDog-Analytics-Schema-0f92f08f72fd4b6a9bc528cd38d02765#c6298b12a46e43c9b3d1cf51d66d47be

**Comment by Cosmin-Parvulescu** [comment]
In the context of our React Native app, we're using the "Touchable" control that doesn't provide any way to add custom attributes as far as I can tell. Would tracking a [Custom Action](https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/?tab=npm#custom-actions) achieve the business goals?

**Comment by Cosmin-Parvulescu** [comment]
Unassigning myself as it's been put on hold for the moment. :)

**Comment by alfl** [comment]
This could probably be done in Expo with custom Javascript actions -- I'll adjust.

**Comment by alfl** [comment]
Update that this still needs to happen. Not a burning fire as the entire button needs to be redesigned and we can track this implicitly in DD.

**Comment by alfl** [comment]
DD is active. Closing for now until we decide this has priority.
