### ISSUE TITLE
chore(sdk): building, packaging, publishing

### ISSUE THREAD

**Issue by crimeminister** [kubelt/kubelt#61]
* `sdk`
  * [x] associate `@kubelt` npm package scope with GitHub package registry
    * this is done via an `.npmrc` under the top-level `sdk/` directory
    * intent is to publish private to GitHub and then eventually publicly to npm (and maybe GitHub) 
* `@kubelt/ddt`
  * [x] ~publish package to GitHub~
  * [ ] write package docs
  * [ ] build pipeline
* `@kubelt/sdk`
  * [x] ~publish npm package to GitHub (compiled to JavaScript)~
  * [x] publish maven package to GitHub (as CLJS library)
  * [ ] write package docs
  * [ ] build pipeline
  * [ ] set default remote address for IPFS client
  * [ ] set default remote address for p2p client (`api.kubelt.com`)
* `@kubelt/web`
  * [x] ~publish package to GitHub~
  * [ ] write package docs
  * [ ] build pipeline 
* `@kubelt/kbt`
  * [x] ~refer to published SDK (cljs) from `shadow-cljs.edn`~ the CLI now depends on the library directly
    * `com.kubelt/sdk "0.0.2"` 
  * [ ] ~enable fetching of private resource~
    * currently we can resolve the coordinate of the dependency
    * however, we are getting an authentication error  
  * [ ] ~publish package to GitHub~
  * [ ] write package docs
  * [ ] build pipeline
__
## notes
* still need to decide on versioning schema, release git flow, tagging, etc.
* need to figure out our preferred error handling strategy
  * e.g.  pass in invalid multiaddress to init, returns error map? throws exception?

**Comment by alfl** [comment]
Per discussion with @drew-patel this seems largely done and description should be refreshed in collaboration with @crimeminister.

**Comment by alfl** [comment]
Let's close for now and revisit.
