### ISSUE TITLE
FEAT(profile): Implement Profile Details Screen

### ISSUE THREAD

**Issue by Cosmin-Parvulescu** [kubelt/kubelt#610]

**Comment by alfl** [comment]
Rather than "extracting" the profile details screen it might be fastest to re-implement from scratch.

**Comment by Cosmin-Parvulescu** [comment]
> Rather than "extracting" the profile details screen it might be fastest to re-implement from scratch.

That's what we've been doing anyway, impossible to translate to Expo layout & css systems.
