### ISSUE TITLE
FEAT(Mint): Create Mint NFT Flow

### ISSUE THREAD

**Issue by Cosmin-Parvulescu** [kubelt/kubelt#624]
We need to add, possibly, a screen with four panels:
- [x] #626
- [x] #662
- [x] #666
- [x] #664
- [ ] CHORE(Mint): Fill pre-mint data
- [ ] CHORE(Mint): Sign voucher

If actions are dropped at any point in the MintPFP funnel, the user should be redirected to the Profile Settings screen and will not be part of this funnel again. They will be able to, in the future, go through the journey manually.

Figma resources:
https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=2143%3A9687

Note:
There are additional screens in Figma. Those selected as part of this FEAT were discussed as part of the alignment / kickoff meeting. Most notable the removal of ENS features.

**Comment by alfl** [comment]
The "Error" case probably most relates to the gas fees spiking during a mint and causing the transaction to fail.
