### ISSUE TITLE
FEAT(mint): Skip Minting

### ISSUE THREAD

**Issue by Cosmin-Parvulescu** [kubelt/kubelt#635]
Route the user to the profile settings screen and write a setting to their profile indicating that they have skipped minting.

**Comment by alfl** [comment]
Yes, and see https://github.com/kubelt/kubelt-oort/issues/160 which depends on https://github.com/kubelt/kubelt-oort/issues/152.

**Comment by Cosmin-Parvulescu** [comment]
Handled in #558
